# inherit_from: .rubocop_todo.yml
Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Style/IfUnlessModifier:
  Exclude:
    - "bin/bundle"

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets
