# inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
