language: ruby

services:
  - postgresql

before_script:
  - bundle exec bin/setup script/createdb.sh RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - psql -c 'create database batabase_test;' -U postgres

script:
  - bundle exec rails webpacker:compile
  - bundle exec rails spec