language: ruby

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - postgresql

cache:
  bundler: true
  directories:
  - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - bundle exec rake db:reset

script:
  - bundle exec rake webpacker:compile
  - bundle exec rspec