language: ruby

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - postgresql

cache:
  bundler: true
  directories:
  - node_modules
  yarn: true

before_script:
  - rake db:reset

script:
  - rake webpacker:compile
  - rspec -f -d