language: ruby

addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - postgresql

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - gem install bundler -v 1.17.3
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - ./script/create-test-db.sh

script:
  - bundle exec rails webpacker:compile
  - bundle exec rails spec