rvm:
  - 2.5.1

addons:
  postgresql: "11.5"

before_script:
  - bundle exec bin/setup script/createdb.sh RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails webpacker:compile
  - bundle exec rails spec