#!/bin/bash

export CI_NAME="heroku"
export GIT_COMMITTED_AT="$(date +%s)"

# run the ruby test suite
yarn add
NODE_ENV=test bundle exec rails webpacker:compile
bundle exec rake spec
RETURN_VALUE=$?

./cc-test-reporter after-build
exit $RETURN_VALUE
