bundle exec rake db:reset
bundle exec rake seed:populate_one_organization
bundle exec rake seed:states
bundle exec rake seed:create_users;
bundle exec rake seed:detection_targets;
bundle exec rake seed:target_descriptors;
bundle exec rake seed:study_areas;
bundle exec rake seed:counties;
bundle exec rake seed:broad_habitats;
bundle exec rake seed:sample_units;
bundle exec rake seed:contact_state_id;
bundle exec rake seed:contact_organization_id;
